BLAN-5252 New Loading Spinner: Fix loading circle width size
bandlab/circle-progress pull request #2
Opened 2019-04-02 09:43 UTC by Thearith

Just to provide a setter for setting donut radius. We need to be able to set this param in run-time.

2019-04-02 09:44 UTC, gildor requested changes

2019-04-02 09:44 UTC, gildor commented on gradle.properties
> +ANDROID_SUPPORT_LIBRARY_VERSION=28.0.0
Can we easily migrate on AndroidX?

2019-04-02 09:46 UTC, Thearith commented on gradle.properties
> +ANDROID_SUPPORT_LIBRARY_VERSION=28.0.0
Okay sure.

2019-04-02 10:03 UTC, gildor requested changes

2019-04-02 10:03 UTC, gildor commented on build.gradle
> +    implementation "androidx.appcompat:appcompat:$ANDROIDX_VERSION"
But looks that we don't need appcompat. `androidx.annotation:annotation:$ANDROIDX_VERSION` should be enough

2019-04-11 01:56 UTC, sarah-nkl approved these changes

2019-04-11 02:43 UTC, Thearith commented
retest this please

2019-04-11 03:31 UTC, gildor approved these changes

2019-04-11 03:31 UTC, merged